### ISSUE TITLE
Reading order

### ISSUE THREAD

**Issue by ghost** [cvlab-stonybrook/Scanpath_Prediction#1]
@ouyangzhibo Thank you for your hard work,
- When will the code be released.
- Can this code be trained to detect the reading order, example: to detect the reading order of textlines within a document image.
- can it run on cpu

**Comment by ouyangzhibo** [comment]
> @ouyangzhibo Thank you for your hard work,
> 
> * When will the code be released.
> * Can this code be trained to detect the reading order, example: to detect the reading order of textlines within a document image.
> * can it run on cpu

**Comment by ouyangzhibo** [comment]
> @ouyangzhibo Thank you for your hard work,
> 
> * When will the code be released.
> * Can this code be trained to detect the reading order, example: to detect the reading order of textlines within a document image.
> * can it run on cpu

Thanks for your interests in our work. 

1. We are working on releasing the code now. It will be done within the next one or two weeks.
2. I am not sure what you mean by reading order, you can read our paper [here](http://www3.cs.stonybrook.edu/~zhibyang/papers/scanpath-Pred_CVPR20.pdf) to see if it suits your task. You may also find the other [project](http://gaze.cs.stonybrook.edu/etra19.html) in our group relevant.
3. The trained model can run on cpu however I wouldn't recommend to train the model using cpu.

**Comment by ghost** [comment]
- Is it better to focus on the `reward` and not `behavior` for learning sequences?

Take this example:
1. My Groundtruth is image documents and their labels of the text regions, example (1st paragraph, 2nd paragraph, 3rd paragraph, etc..)
2. I want to train a model to learn the concept of `reading order`.
3. Finally, I will use the trained model on image documents with text regions, example ( paragraph, paragraph, paragraph), and the model would tell which paragraph is 1st, which is 2nd, etc...

For this task, do you recommend `Inverse RL`, or `RL`?
Any specific RL algorithm do you recommend? @ouyangzhibo 

![readingorder](https://user-images.githubusercontent.com/49877135/82130193-e12cf380-97d1-11ea-8ed1-07f864e3ac51.jpg)

**Comment by ouyangzhibo** [comment]
> * Is it better to focus on the `reward` and not `behavior` for learning sequences?
> 
> Take this example:
> 
> 1. My Groundtruth is image documents and their labels of the text regions, example (1st paragraph, 2nd paragraph, 3rd paragraph, etc..)
> 2. I want to train a model to learn the concept of `reading order`.
> 3. Finally, I will use the trained model on image documents with text regions, example ( paragraph, paragraph, paragraph), and the model would tell which paragraph is 1st, which is 2nd, etc...
> 
> For this task, do you recommend `Inverse RL`, or `RL`?
> Any specific RL algorithm do you recommend? @ouyangzhibo
> 
> ![readingorder](https://user-images.githubusercontent.com/49877135/82130193-e12cf380-97d1-11ea-8ed1-07f864e3ac51.jpg)

Do you have the ground-truth human reading order? If so, your problem is similar to ours. This is essentially an imitation learning problem, in which you basically have two solutions---inverse reinforcement learning (IRL) and behavior cloning. I cannot say which is better in your task. In our work, we (and many psychologists) think the task we dealt with, visual search, is a reinforcement learning problem, so we use IRL. You can try both.

For IRL algorithm, you can start with the one we use in our work (GAIL), please find detail in our paper.

**Comment by ghost** [comment]
- i have the ground-truth in reading order, it consists of a combination of images and their xml labels, which contains the coordinates of each text region.
- i am eagerly waiting for you to publish the training and inferencing code.

**Comment by deepseek** [comment]
why `max_traj_length` is set to only 6? does increasing the trajectory maximum point reduce accuracy?

**Comment by ouyangzhibo** [comment]
> why `max_traj_length` is set to only 6? is that because it yields better results for coco18?
> does increasing the trajectory maximum point reduce accuracy?
> I am asking because in some cases i might have more than 30 text lines to predict their reading order.

6 is roughly the average scanpath length in COCO18, and larger than the length of most of the scanpath target-present trials in our dataset. Note that setting a `max_traj_length` is to prevent the generator from generating an infinitely long scanpath which hurts the training efficiency.

Increasing `max_traj_length` does not necessary reduce the performance, because in our case, the scanpath naturally stops when finding the target. I guess in your case, you probably need to design or learn some scanpath termination rule.
